---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
Loblolly
summary(Loblolly)
```
```{r}
cor(Loblolly[,sapply(Loblolly, is.numeric)], use="complete.obs")
```



```{r}
ggplot(Loblolly, aes(x = age,y = height, color = Seed))+
  geom_point()+
  geom_line()
```



```{r}
# group map also a possibility

Loblolly_with_predictions <- Loblolly %>%
  group_by(Seed) %>%
  group_modify(~ {
    model <- nls(height ~ k*(1-(3/age))^b, data = .x, start = list(k = 60,b = 4))
    .x$predicted <- predict(model)
    .x
  })
```

```{r}
Loblolly_with_predictions %>%
  filter(Seed == 329) %>%
ggplot(aes(x = age, y = height, color = Seed)) +
  geom_point() +  # Original data points
  geom_line(aes(y = predicted), linetype = "dashed") +  # Fitted lines
  labs(title = "Fitted Exponential Model for Each Seed Group",
       x = "Age", y = "Height") +
  theme_minimal()
```
```{r}
# R example code
require(stats); require(graphics)
plot(height ~ age, data = Loblolly, subset = Seed == 329,
     xlab = "Tree age (yr)", las = 1,
     ylab = "Tree height (ft)",
     main = "Loblolly data and fitted curve (Seed 329 only)")
fm1 <- nls(height ~ SSasymp(age, Asym, R0, lrc),
           data = Loblolly, subset = Seed == 329)
age <- seq(0, 30, length.out = 101)
lines(age, predict(fm1, list(age = age)))

# subset is a nice way to quickly filter for a simple plot without dplyr %>%
```

applying this princicple to my code

```{r}
# group map also a possibility

Loblolly_with_predictions <- Loblolly %>%
  group_by(Seed) %>%
  group_modify(~ {
    model <- nls(height ~ SSasymp(age, Asym, R0, lrc), data = .x)
    .x$predicted <- predict(model)
    .x
  })
```

```{r}
Loblolly_with_predictions %>%
  filter(Seed == 329) %>%
ggplot(aes(x = age, y = height, color = Seed)) +
  geom_point() +  # Original data points
  geom_line(aes(y = predicted), linetype = "dashed") +  # Fitted lines
  labs(title = "Fitted Exponential Model for Each Seed Group",
       x = "Age", y = "Height") +
  theme_minimal()
```
```{r}
# report stats from auto fitting

model <- nls(height ~ SSasymp(age, Asym, R0, lrc), data = Loblolly, subset = Seed == 329)
summary(model)
```
```{r}
# lets test this model for viability at a range of tree ages

xvals <- seq(0, 100, 0.001)
yvals <- 94.1282 + (-8.2508 - 94.1282) * exp(-exp(-3.2176) * xvals)
plot(xvals, yvals, type = "l")

# seems feasible for ages 5 - 100? data doesn't go far enough but obviously -8.25 is not a valid height for a nascent sapling :(
```






